apiVersion: apps/v1
kind: Deployment
metadata:
  name: configDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configDeployment
  template:
    metadata:
      labels:
        app: configDeployment
    spec:
      containers:
        - name: config-service
          image: eliaszngusach/config-service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  selector:
    app: configDeployment
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer