apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-deployment
  labels:
    app: eureka-deployment
spec:
  selector:
    matchLabels:
      app: eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-deployment
    spec:
      containers:
        - name: eureka-service
          image: eliaszngusach/eureka-service:latest
          ports:
            - containerPort: 8761
          env:
          # --- ESTO CONECTA EUREKA CON EL CONFIG SERVER ---
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8081"
          - name: EUREKA_INSTANCE_HOSTNAME
            value: "localhost"
          - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
            value: "false"
          - name: EUREKA_CLIENT_FETCH_REGISTRY
            value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer