apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaDeployment
  labels:
    app: eurekaDeployment
spec:
  selector:
    matchLabels:
      app: eurekaDeployment
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaDeployment
    spec:
      containers:
        - name: eureka-service
          image: eliaszngusach/eureka-service:latest
          ports:
            - containerPort: 8761
          env:
          # --- ESTO CONECTA EUREKA CON EL CONFIG SERVER ---
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-service:8081"
          - name: EUREKA_INSTANCE_HOSTNAME
            value: "localhost"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka-service
spec:
  selector:
    app: eurekaDeployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: LoadBalancer