apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendDeployment
  labels:
    app: frontendDeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontendDeployment
  template:
    metadata:
      labels:
        app: frontendDeployment
    spec:
      containers:
      - name: frontend
        image: eliaszngusach/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontendDeployment
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort  # Exposici√≥n del puerto 80 del frontend en el puerto 30000